### ISSUE TITLE
USER STORY: Submit answer

### ISSUE THREAD

**Issue by Bruno-Diego** [Bruno-Diego/ci-love-running#1]
As a **user** I can **select and submit an answer from the poll** so that **I give my opinion about a topic or an event**.

**Comment by Bruno-Diego** [comment]
# Acceptance Criteria:
* The answers should be multiple choices as radial buttons
* One answer should be “selected” by default
* The multiple choices should appear above the submit button
* After submitting, a submission confirmation should be displayed.

# Tasks:
- [ ] Update the view: the poll design (HTML and CSS) to include the question followed by multiple choice answers selectable by radial buttons
- [ ] Make one of the answers selected by default
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
