### ISSUE TITLE
USER STORY: Publish a poll

### ISSUE THREAD

**Issue by Bruno-Diego** [Bruno-Diego/ci-love-running#4]
As a **administrator** I can **publish a poll** so that **I collect users' feedback**.

**Comment by Bruno-Diego** [comment]
# Acceptance Criteria:
 * The option should be provided as form
 * The form should be empty for the administrator to create the questions and answers
 * The form should have a button to create the poll
 * After creating the poll, the administrator receive an e-mail with the users answers

# Tasks
- [ ] Create the admin module view: the poll design (HTML and CSS) to include a form to create a poll
- [ ] Create a Javascript function to create the poll in the main page based on the data provided by the form.
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
