### ISSUE TITLE
USER STORY: Poll expiry date

### ISSUE THREAD

**Issue by Bruno-Diego** [Bruno-Diego/ci-love-running#5]
As a **administrator** I can **pick the expiry date when publishing the poll** so that **the poll hides automatically**.

**Comment by Bruno-Diego** [comment]
# Acceptance Criteria:
 * The option should be provided as a date type input
 * The date should be undefined by default
 * The option should appear before to the create poll button
 * After publishing, the poll will automatically be hidden when the chosen date expires.

# Tasks:
- [ ] Update the admin module view: the poll design (HTML and CSS) to include date picker
- [ ] Update the website view: show "Stay tuned, a new poll is coming soon"
- [ ] Create a Javascript function to validate the expiry date is at least after 3 days.
- [ ] Create a job to check expired Polls everyday at 11:59 PM and Hide them
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
